import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
import {runInNewContext} from 'node:vm';

const html=readFileSync(new URL('../src/tori_taurus/scanner.html',import.meta.url),'utf8');
const source=html.split('// BEGIN RESEARCH RANKING:')[1].split('// END RESEARCH RANKING')[0];
const score=runInNewContext('// BEGIN RESEARCH RANKING:'+source+'\nscoreCandidate');
const now=Date.parse('2026-10-09T14:00:00Z');
const fixture=()=>({symbol:'ABC',change_percent:'8',quote:{fresh:true,session:'regular',timestamp:new Date(now).toISOString(),bid:'1.998',ask:'2.002'},plan:{setup:'first_pullback',entry:'2.01',stop:'1.96',state:'SETUP CONFIRMED'},report:{setups:{first_pullback:{state:'CONFIRMED'}},intraday:{last_close:'2',vwap:'1.98',relative_volume:'3'},daily_scan:{features:{close:'1.9',ema5:'1.9',ema9:'1.8',ema20:'1.7',daily_relative_volume:'2'}}}});
test('fixed score has a transparent sum and missing social does not inflate it',()=>{const r=score(fixture(),'live',null,now);assert.equal(r.eligible,true);assert.equal(r.score,93);assert.equal(r.evidence,95);assert.equal(r.score,r.parts.reduce((n,p)=>n+p.points,0));assert.ok(r.missing.includes('Public social sample'));});
test('stale, future, closed-session, wide-spread and missing setup candidates cannot qualify',()=>{for(const mutate of [c=>c.quote.timestamp=new Date(now-60001).toISOString(),c=>c.quote.timestamp=new Date(now+1).toISOString(),c=>c.quote.session='postmarket',c=>c.quote.bid='1.8',c=>c.report.setups.first_pullback.state='INVALIDATED',c=>c.plan.stop=null,c=>c.warning='Incomplete bars']){const c=fixture();mutate(c);assert.equal(score(c,'live',null,now).eligible,false);}});
test('missing factors earn zero and historical volume is capped at six',()=>{const c=fixture();delete c.report.intraday.relative_volume;c.report.daily_scan.features.daily_relative_volume='100';let r=score(c,'live',null,now);assert.equal(r.parts.find(x=>x.name==='Volume participation').points,6);c.report.intraday={};c.report.daily_scan={};r=score(c,'live',null,now);assert.equal(r.parts.find(x=>x.name==='Volume participation').points,0);assert.equal(r.parts.find(x=>x.name==='Trend / extension').points,0);assert.ok(r.evidence<95);});
test('risk block remains explicit and scoring never mutates plans',()=>{const c=fixture();c.plan.state='RISK BLOCKED';const before=JSON.stringify(c);const r=score(c,'live',null,now);assert.equal(JSON.stringify(c),before);assert.ok(r.cautions.some(x=>x.includes('risk rules block')));});
test('only fresh manual social evidence contributes; demo and saved reports never do',()=>{const social={kind:'Manual scan',collected_at:new Date(now).toISOString(),symbols_checked:['ABC'],coverage:[{status:'sampled recent posts',posts:10}],tickers:[{symbol:'ABC',mentions:10,unique_authors:10,sentiment:'positive'}]};assert.equal(score(fixture(),'live',social,now).score,98);for(const mutate of [s=>s.kind='Saved sample',s=>s.collected_at=new Date(now-3600001).toISOString(),s=>s.collected_at=new Date(now+1).toISOString(),s=>s.symbols_checked=['XYZ'],s=>s.coverage=[{status:'unavailable',posts:null}]]){const s=structuredClone(social);mutate(s);assert.equal(score(fixture(),'live',s,now).score,93);}assert.equal(score(fixture(),'demo',social,now).score,93);social.tickers[0].sentiment='negative';assert.ok(score(fixture(),'live',social,now).cautions.some(x=>x.includes('leans negative')));});
test('premarket levels qualify as research only and independently expire',()=>{const c=fixture();c.quote.session='premarket';c.quote.fresh=false;c.plan.entry=null;c.plan.stop=null;c.report.premarket_research={quote_at:new Date(now).toISOString(),conditional_entry:'2.01',invalidation:'1.96',last:'2'};const r=score(c,'live',null,now);assert.equal(r.eligible,true);assert.equal(r.session,'Premarket research');assert.equal(r.parts[0].points,12);assert.ok(r.cautions.some(x=>x.includes('Premarket research only')));c.report.premarket_research.quote_at=new Date(now-60001).toISOString();assert.equal(score(c,'live',null,now).eligible,false);});
